### ISSUE TITLE
Where can I find the end-user installation files? 

### ISSUE THREAD

**Issue by typothecary** [mhmoodlan/SubX#2]
Hi - this program was recommended to me but what seems to be the original site for end-user installation (elfdata.com)  is closed. Can you help with a link, please?

**Comment by mhmoodlan** [comment]
This repository is the original source of this program -not elfdata.com.
For the end-user installation you can find it here: 
[end-user installation](https://github.com/mhmoodlan/SubX/releases/download/v1.0/SubX-v1.0.rar)

For more details on how to install and use it check this:
[guide](https://mhmoodlan.github.io/SubX/)

**Comment by typothecary** [comment]
Thank you - I appreciate your help.
